version: 1
groups:
  - annotation: ckanext-charts
    options:
      - key: ckanext.charts.cache_strategy
        description: Charts cache strategy
        default: redis
        editable: true
        validators: OneOf(["file","redis"])

      - key: ckanext.charts.redis_cache_ttl
        description: Redis cache TTL
        default: 3600
        editable: true
        type: int
        validators: ignore_empty int_validator

      - key: ckanext.charts.file_cache_ttl
        description: File cache TTL
        default: 3600
        editable: true
        type: int
        validators: ignore_empty int_validator

      - key: ckanext.charts.enable_cache
        description: Enable cache
        default: true
        editable: true
        type: bool
        validators: ignore_empty boolean_validator

      - key: ckanext.charts.include_htmx_asset
        description: Include HTMX asset
        default: true
        type: bool
        validators: ignore_empty boolean_validator
